services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:soujaour
    container_name: mariadb
    expose:
      - 3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:soujaour
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    environment:
      - DOMAIN_NAME
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - WP_ADMIN_USER
      - WP_ADMIN_PASSWORD
      - WP_USER
      - WP_USER_PASSWORD
    depends_on:
      - mariadb
      - redis
    networks:
      - inception
    expose:
      - 9000
    restart: always

  nginx:
    build: ./requirements/nginx
    image: nginx:soujaour
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  static:
    build: ./requirements/bonus/static
    image: static:soujaour
    container_name: static
    ports:
      - "8080:80"
    networks:
      - inception
    restart: always

  redis:
    build: ./requirements/bonus/redis
    image: redis:soujaour
    container_name: redis
    networks:
      - inception
    ports:
      - "6379:6379"
    restart: always

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp:soujaour
    container_name: ftp
    env_file: .env
    environment:
      - FTP_USER
      - FTP_PASSWORD
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    restart: always

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:soujaour
    container_name: adminer
    networks:
      - inception
    ports: 
      - "8081:80"
    depends_on: 
      - mariadb
    restart: always
  
  uptimer:
    build: ./requirements/bonus/uptimer
    image: uptimer:soujaour
    container_name: uptimer
    networks:
      - inception
    ports:
      - "3001:3001"
    volumes:
      - uptimer:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/soujaour/data/db
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/soujaour/data/wp
      o: bind
  uptimer:
    name: uptimer
    driver: local
    driver_opts:
      type: none
      device: /home/soujaour/data/uptimer
      o: bind
